/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ErrorToast: typeof import('./src/components/ErrorToast.vue')['default']
    GroupCard: typeof import('./src/components/GroupCard.vue')['default']
    LocationPickerMap: typeof import('./src/components/LocationPickerMap.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
