/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next/components/BForm')['BFormInvalidFeedback']
    ErrorToast: typeof import('./src/components/ErrorToast.vue')['default']
    GroupCard: typeof import('./src/components/GroupCard.vue')['default']
    JoinGroupModal: typeof import('./src/components/JoinGroupModal.vue')['default']
    LocationPickerMap: typeof import('./src/components/LocationPickerMap.vue')['default']
    MemberCard: typeof import('./src/components/MemberCard.vue')['default']
    MultiItemMap: typeof import('./src/components/MultiItemMap.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PlaceCard: typeof import('./src/components/PlaceCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareGroupModal: typeof import('./src/components/ShareGroupModal.vue')['default']
  }
}
